In [1]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path
import numpy as np
from scipy import stats
from scipy.stats import linregress
import scipy.stats as st
import sys

In [2]:
# Load the data file, read and display it with Pandas
bridge_data = Path("Philadelphia Cleaned DOT Data.csv")

In [3]:
bridge_df = pd.read_csv(bridge_data)

bridge_df

,Latitude,Longitude,Year Built,Owner,Maintenance Responsibility,Bridge Condition,Bridge Improvement Cost,Roadway Improvement Cost,Total Improvement Cost,Year Reconstructed,Deck Width,Structure Length
0,40.103450,-74.961092,1990,4,4,G,0.0,0.0,0.0,0.0,13.0,18.3
1,39.989944,-75.250461,1935,1,27,F,86.0,252.0,1156.0,0.0,19.1,28.7
2,40.000700,-75.227539,1910,1,1,P,25.0,72.0,332.0,0.0,25.3,18.9
3,40.006661,-75.199589,1953,1,1,F,0.0,0.0,0.0,1989.0,14.9,50.3
4,40.007103,-75.192278,1960,1,1,F,605.0,1782.0,8168.0,NaN,13.6,587.0
...,...,...,...,...,...,...,...,...,...,...,...,...
588,39.971314,-75.123447,2019,1,1,G,NaN,NaN,NaN,NaN,22.3,238.4
589,39.942597,-75.211397,2020,27,27,G,NaN,NaN,NaN,NaN,24.2,15.2
590,40.058022,-75.195347,2020,1,1,G,NaN,NaN,NaN,NaN,15.2,16.8
591,39.998933,-75.086278,2021,1,1,G,NaN,NaN,NaN,NaN,29.5,56.7
592,39.893306,-75.191028,1941,26,26,F,NaN,NaN,NaN,2003.0,12.5,120.4

In [4]:
# Add a square ft column to the data frame
bridge_df.loc[:,"SqFt"] = bridge_df["Deck Width"] * bridge_df["Structure Length"]
bridge_df

,Latitude,Longitude,Year Built,Owner,Maintenance Responsibility,Bridge Condition,Bridge Improvement Cost,Roadway Improvement Cost,Total Improvement Cost,Year Reconstructed,Deck Width,Structure Length,SqFt
0,40.103450,-74.961092,1990,4,4,G,0.0,0.0,0.0,0.0,13.0,18.3,237.90
1,39.989944,-75.250461,1935,1,27,F,86.0,252.0,1156.0,0.0,19.1,28.7,548.17
2,40.000700,-75.227539,1910,1,1,P,25.0,72.0,332.0,0.0,25.3,18.9,478.17
3,40.006661,-75.199589,1953,1,1,F,0.0,0.0,0.0,1989.0,14.9,50.3,749.47
4,40.007103,-75.192278,1960,1,1,F,605.0,1782.0,8168.0,NaN,13.6,587.0,7983.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,39.971314,-75.123447,2019,1,1,G,NaN,NaN,NaN,NaN,22.3,238.4,5316.32
589,39.942597,-75.211397,2020,27,27,G,NaN,NaN,NaN,NaN,24.2,15.2,367.84
590,40.058022,-75.195347,2020,1,1,G,NaN,NaN,NaN,NaN,15.2,16.8,255.36
591,39.998933,-75.086278,2021,1,1,G,NaN,NaN,NaN,NaN,29.5,56.7,1672.65
592,39.893306,-75.191028,1941,26,26,F,NaN,NaN,NaN,2003.0,12.5,120.4,1505.00

In [5]:
# Add column for cost to repair by multipling the SqFt by the cost to repair figures calculated by the US DOT FHA
bridge_df.loc[:,"Repair Cost Est"] = bridge_df["SqFt"] * 314
bridge_df

,Latitude,Longitude,Year Built,Owner,Maintenance Responsibility,Bridge Condition,Bridge Improvement Cost,Roadway Improvement Cost,Total Improvement Cost,Year Reconstructed,Deck Width,Structure Length,SqFt,Repair Cost Est
0,40.103450,-74.961092,1990,4,4,G,0.0,0.0,0.0,0.0,13.0,18.3,237.90,74700.60
1,39.989944,-75.250461,1935,1,27,F,86.0,252.0,1156.0,0.0,19.1,28.7,548.17,172125.38
2,40.000700,-75.227539,1910,1,1,P,25.0,72.0,332.0,0.0,25.3,18.9,478.17,150145.38
3,40.006661,-75.199589,1953,1,1,F,0.0,0.0,0.0,1989.0,14.9,50.3,749.47,235333.58
4,40.007103,-75.192278,1960,1,1,F,605.0,1782.0,8168.0,NaN,13.6,587.0,7983.20,2506724.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,39.971314,-75.123447,2019,1,1,G,NaN,NaN,NaN,NaN,22.3,238.4,5316.32,1669324.48
589,39.942597,-75.211397,2020,27,27,G,NaN,NaN,NaN,NaN,24.2,15.2,367.84,115501.76
590,40.058022,-75.195347,2020,1,1,G,NaN,NaN,NaN,NaN,15.2,16.8,255.36,80183.04
591,39.998933,-75.086278,2021,1,1,G,NaN,NaN,NaN,NaN,29.5,56.7,1672.65,525212.10
592,39.893306,-75.191028,1941,26,26,F,NaN,NaN,NaN,2003.0,12.5,120.4,1505.00,472570.00

In [6]:
# Add column for cost to replace by multipling the SqFt by the cost to replace (cost to replace * 1.32) figures calculated by the US DOT FHA
bridge_df.loc[:,"Replacement Cost Est"] = bridge_df["SqFt"] * 414.48
bridge_df

,Latitude,Longitude,Year Built,Owner,Maintenance Responsibility,Bridge Condition,Bridge Improvement Cost,Roadway Improvement Cost,Total Improvement Cost,Year Reconstructed,Deck Width,Structure Length,SqFt,Repair Cost Est,Replacement Cost Est
0,40.103450,-74.961092,1990,4,4,G,0.0,0.0,0.0,0.0,13.0,18.3,237.90,74700.60,9.860479e+04
1,39.989944,-75.250461,1935,1,27,F,86.0,252.0,1156.0,0.0,19.1,28.7,548.17,172125.38,2.272055e+05
2,40.000700,-75.227539,1910,1,1,P,25.0,72.0,332.0,0.0,25.3,18.9,478.17,150145.38,1.981919e+05
3,40.006661,-75.199589,1953,1,1,F,0.0,0.0,0.0,1989.0,14.9,50.3,749.47,235333.58,3.106403e+05
4,40.007103,-75.192278,1960,1,1,F,605.0,1782.0,8168.0,NaN,13.6,587.0,7983.20,2506724.80,3.308877e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,39.971314,-75.123447,2019,1,1,G,NaN,NaN,NaN,NaN,22.3,238.4,5316.32,1669324.48,2.203508e+06
589,39.942597,-75.211397,2020,27,27,G,NaN,NaN,NaN,NaN,24.2,15.2,367.84,115501.76,1.524623e+05
590,40.058022,-75.195347,2020,1,1,G,NaN,NaN,NaN,NaN,15.2,16.8,255.36,80183.04,1.058416e+05
591,39.998933,-75.086278,2021,1,1,G,NaN,NaN,NaN,NaN,29.5,56.7,1672.65,525212.10,6.932800e+05
592,39.893306,-75.191028,1941,26,26,F,NaN,NaN,NaN,2003.0,12.5,120.4,1505.00,472570.00,6.237924e+05